spring:
  datasource:
    username: root
    password: 1234
    #hikari:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    root: info
    sql: debug

jwt:
  secret-key: UUQ8mYSm5xX3Y04qYYoT310L22J3kR4AVf4mv3cXQ8hKe6n2uMOBY7UNldskIdWT
  access-token-validity: 86400
  refresh-token-validity: 186400

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/test_auth?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config:
    activate:
      on-profile: mariadb
  datasource:
    url: jdbc:mariadb://localhost:3307/test_auth?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
